trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands:
      - npm

variables:
  buildConfiguration: 'Release'
  
steps:
# Install npm packages
- script: npm install
  displayName: 'Install npm'

# Run the tests
- script: npm test 
  displayName: 'Integration test front'

# Publish the coverage reports and fail if some test fail
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs: 
    codeCoverageTool: Cobertura 
    summaryFileLocation: '**/*coverage.xml'
    reportDirectory: '**/coverage'
    failIfCoverageEmpty: true

# Generate the production version
- script: npm run build
  displayName: 'Build React project'
  