# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands:
      - npm

variables:
  buildConfiguration: 'Release'
  

steps:
- script: npm install
  displayName: 'Install npm'

- script: npm test 
  displayName: 'Integration test front'
  workingDirectory: $(frontDir)

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs: 
    codeCoverageTool: Cobertura 
    summaryFileLocation: '**/*coverage.xml'
    reportDirectory: '**/coverage'
    failIfCoverageEmpty: true

- script: npm run build
  displayName: 'Build React project'
  